digitaldemocracy2030/kouchou-ai

.env.example
compose.yaml
server/src/config.py
server/src/main.py

* 環境(development/production)を示す環境変数を追加
* productionの場合はopenapi等のuiを表示しないように修正
* 本番環境において、APIの情報を表示させたくない
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](/CLA.md)に同意することが必須です。

production環境ではopen api ui等を表示しない

---

client-admin/middleware.ts

環境変数 BASIC_AUTH_USERNAME, BASIC_AUTH_PASSWORD が空文字列の場合も Basic 認証をスキップするようにします
#63 環境変数がセットされていない場合でも、認証がスキップされない
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](/CLA.md)に同意することが必須です。

fix: 環境変数 BASIC_AUTH_* に値を設定しない場合でも Basic 認証が求められてしまう

---

client/components/Header.tsx

- fixes https://github.com/takahiroanno2024/kouchou-ai/issues/45
docker compose で起動すると、Header コンポーネントの画像のパスが `http://api:8000/meta/reporter.png` を指していて、適切に画像が表示されない課題を修正しました。
- 原因: Header コンポーネントが Server Component としてレンダリングされるため、[画像のパスを取得する際に利用する関数内で `http://api:8000` が Base URL として返されている](https://github.com/takahiroanno2024/kouchou-ai/blob/9e2c9f64f2806bee5946e6939157b3541178b5a8/client/app/utils/api.ts#L6-L8)
- 修正方針: Header コンポーネントを Client Component としてレンダリングすることで、期待した Base URL を取得できるようにする
- Header コンポーネントと同じ画像を参照している [About コンポーネントが Client Component](https://github.com/takahiroanno2024/kouchou-ai/blob/9e2c9f64f2806bee5946e6939157b3541178b5a8/client/components/About.tsx#L1-L24) で適切にレンダリングできていたので、そちらに寄せました
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](/CLA.md)に同意することが必須です。 …

fix: docker-composeで起動した際に、clientで一部の画像が表示されない

---

client-admin/app/page.tsx
server/broadlistening/pipeline/specs.json

バックエンド側のステータス変更については問題なさそうでしたが、レポート一覧画面でレポート生成失敗時の表示に関する定義がなかったため、追加してみました。
CircleAlertIcon やカラーコードは仮で入れてみたので、違和感あるようであれば適宜修正いただけると幸いです。
#47 
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](/CLA.md)に同意することが必須です。

レポート生成失敗時のレポート一覧画面の表示を調整

---

client/components/charts/ScatterChart.tsx

色盲の方でも視認性の高いチャート配色にするため、各クラスタとアノテーションラベルのカラーコードの指定をするようにしました。
アノテーションラベルについては、borderRadius の指定をする方法を見つけられなかったので一旦指定しない状態にしてみています。
https://plotly.com/javascript/reference/layout/annotations/
#51 
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](https://github.com/takahiroanno2024/kouchou-ai/blob/main/CLA.md)に同意することが必須です。

視認性の高い配色、アノテーションに変更

---

client-admin/Dockerfile
client-admin/package-lock.json
client/Dockerfile
client/package-lock.json

- Dockerfile の node:18 を node:22 に修正
- package-lock.json の audit fix
- Node.js の 18 が今年春にEOLになるのを見越して active な 22 に更新
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](https://github.com/takahiroanno2024/kouchou-ai/blob/main/CLA.md)に同意することが必須です。

upgrade node v18 to v22

---

.github/workflows/client-admin-build.yml
.github/workflows/client-build.yml

- フロントエンドのアプリケーション（client, client-admin）のビルドをチェックする CI を追加しました
- client, client-admin の各ディレクトリのファイルを変更したら、それぞれのビルドが CI で実行されます
- fix: #73 
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](https://github.com/takahiroanno2024/kouchou-ai/blob/main/CLA.md)に同意することが必須です。

フロントエンドのアプリケーションのビルドをチェックする CI を追加

---

client-admin/Dockerfile

- https://github.com/digitaldemocracy2030/kouchou-ai/pull/74 で追加したサンプルファイルが Docker 環境だとダウンロードできない不具合を修正しました
- client-admin の Dockerfile 内で、サンプルファイルが格納されている public ディレクトリが COPY されていなかった
Slack での報告スレッド: https://w1740803485-clv347541.slack.com/archives/C08F7JZPD63/p1742284927003429

Docker 環境でサンプルファイルの DL が 404 になる不具合を修正

---

.github/workflows/client-build.yml

- https://github.com/digitaldemocracy2030/kouchou-ai/pull/81 で導入した client のビルドの CI がエラーでこけていたので修正しました 🙏 
- ref: https://github.com/digitaldemocracy2030/kouchou-ai/actions/runs/13916399265
- 原因: ビルド時に参照する環境変数が足りていませんでした
- [client/.env-sample ](https://github.com/digitaldemocracy2030/kouchou-ai/blob/main/client/.env-sample)を元に環境変数の設定を追加しました
- 自分のリポジトリで GitHub Actions を起動して、ビルドが通ることを確認しました
- https://github.com/shgtkshruch/kouchou-ai/actions/runs/13917048914
- client-admin は環境変数がなくてもビルドが通るので、一旦そのままにしています
- https://github.com/shgtkshruch/kouchou-ai/actions/runs/13917035834/job/38941839876
特になし

client の CI のエラーを修正

---

.github/workflows/assign-bot.yml
CONTRIBUTING.md

- Issue上で、`/assign` というコメントをすると自身をasigneeにするworkflowを実装
- 同様に `/unassign` を実装
- どちらのコマンドも、別repoで動作について確認済み
- （本来アサイン権限のない）repo owner以外のアカウントでコメントし、assign/unassignどちらも動作した
- ユーザーの権限によってIssueのアサインをできないケースがあるため、github actionsで同等の操作を実現した
https://github.com/digitaldemocracy2030/kouchou-ai/issues/95

GitHub Actionsでself-assignを可能にする

---

client/app/[slug]/page.tsx
client/components/report/BackButton.tsx

- レポート画面に一覧に戻るボタンを追加しました
- `/components/report` 以下に戻るボタンのコンポーネントを追加しました
- 戻るボタンを表示する場所はページの内容を見てからが良さそう？と思ったので、ページの下部で共通コンポーネントの上部に配置しました
- 前の画面に戻るというよりも、一覧ページに戻る意味合いが強いかなと思ったので、固定でパスを指定しています
- 既存の実装を参考に実装してみたのですが、流儀がわかっていないので何かあればコメントお願いします 🙏 
- fix: https://github.com/digitaldemocracy2030/kouchou-ai/issues/57

レポート画面に一覧へ戻るボタンを追加

---

Makefile
server/Dockerfile
server/broadlistening/pipeline/services/llm.py
server/broadlistening/pipeline/steps/embedding.py

- apiのlintについて、docker上で実行できるようにした
- CIでlintエラーが出ていた箇所も修正
- Makefileにlint/format実行のコマンドを用意した
- docker環境を準備しているにもかかわらず、ruffの実行がホストマシンに依存していた
https://github.com/digitaldemocracy2030/kouchou-ai/issues/108

docker上でapiのlintを実行

---

client/components/charts/TreemapChart.tsx

- ツリーマップに各クラスタの件数を表示するテキストを追加しました
- クラスタ毎に何件あるのかを把握したい要望があるため
- fix: https://github.com/digitaldemocracy2030/kouchou-ai/issues/17

ツリーマップで各クラスタの件数を表示する

---

client-admin/components/Header.tsx
client/components/Header.tsx

close #106 
- client
- ヘッダーの掛け算から右側を削除
- client-admin
- ヘッダーの掛け算から右側を削除
> - 上記ロゴの掛け算の右側はないほうがよいかと思います
>    - 自治体、政党などがより使いやすくなる
>    - ユーザーにとっても初見で情報が多すぎなくて済む
#106 

ロゴの掛け算の右側を削除

---

client-admin/app/create/page.tsx
server/src/schemas/admin_report.py
server/src/services/report_launcher.py

* client-admin側で、OpenAI APIの並列実行数を設定可能にした
* api側で、extraction, initial labelling, merge labellingの各プロセスで設定された並列実行数でAPIを実行するようにした
client-admin上での設定画面
- OpenAI APIの並列実行数が固定化されていた
- [APIのレートリミットはアカウントのtierによって異なる](https://platform.openai.com/docs/guides/rate-limits#free-tier-rate-limits)ため、固定化されていると以下の問題が起きうる
- tierの低いアカウントではレポート出力が失敗する
- tierの高いアカウントではレポート出力まで不要に待たなければならない
https://github.com/digitaldemocracy2030/kouchou-ai/issues/92
https://github.com/digitaldemocracy2030/kouchou-ai/issues/93

レポート作成画面でOpenAI APIの並列実行数をパラメータとして追加

---

client-admin/app/create/page.tsx
client-admin/components/ui/file-upload.tsx

close #100 
- CSVのアップロード後の画面を修正した
- ファイルをアップロード後、アップロードUIを灰色にし無効化
- アップロードされたファイルに削除ボタンを表示
- #100 
#100 

CSVのアップロード後の画面を修正

---

client-admin/app/create/page.tsx
client/components/charts/SelectChartButton.tsx
client/components/report/Analysis.tsx
client/components/report/ClusterBreadcrumb.tsx
client/components/report/DensityFilterSettingDialog.tsx

- UIに関連する部分のみ「クラスタ」を「意見グループ」に修正
レポートを見るユーザーに対して分かりやすくするという意図だと思うので、一括置換せず、以下の箇所は一旦「クラスタ」のままにしました。
- 内部処理に影響しそうな部分（プロンプトなど）
- Analysis パート（分析する/分析内容を確認したい人は、クラスタというキーワードのほうが適切？）
#110 
- レポート生成ページ
- レポート表示のUI部分（ボタン）
- レポート表示部分（濃い意見グループ設定の中）

UIの「クラスタ」を「意見グループ」に修正

---

.github/dependabot.yml

* dependabotの設定ファイルを設置し、パッケージアップデートのPR作成が自動で行われるようにした
* セキュリティの脆弱性に伴うパッケージのアップデートを行いたいが、現状でもgithub上の Security でアラートはくるが、パッケージアップデートをする際は手作業が入る
* -> dependabotで自動化する
https://github.com/digitaldemocracy2030/kouchou-ai/issues/151

dependabotを導入

---

client-admin/app/create/page.tsx

- レポート作成ボタンクリック時にCSVファイルの行数とクラスタ数の設定を比較し、ファイルの行数が少ない場合に警告を出す。
- デフォルトのクラスタ数設定は[5, 50]。
- 登録されたCSVファイルの意見数が設定されたクラスタ数に満たない場合、クラスタリングの過程でエラーになる。
- これを防ぐため、APIを呼び出す前にCSVファイル内のコメント数（ファイルの行数）を確認する。
- コメント数＝意見数ではなく、一つのコメントから複数の意見が抽出される可能性もあるため、エラーではなく警告にとどめる。
Closes #147 

CSVファイル送信時にコメント数とクラスタ数設定を比較して警告を出す

---

scripts/fetch_reports.py

- [FEATURE]resultをローカル環境へ取得するscriptをつくる · Issue #179 
- リモートのAPIサーバURLを指定すると
- GET /reports を叩いて全レポートのslugを取得する
- GET /reports/{slug}を叩いて個別のレポートのresultを取得する
- ローカル環境に適切に配置し、server/data/report_status.jsonを更新する
- 現状リモート環境で作成されたレポートを手元に取得したりバックアップしたりする手軽な手段がなく、再起動の際に成果が失われてしまうため
#179

resultをローカル環境へ取得するscriptをつくる

---

client/components/report/Analysis.tsx
client/components/report/ClusterOverview.tsx
client/components/report/Overview.tsx

- クラスタタイトル下の「33議論」等の表現は「33件」という表現に変える
- Analysis内で使われている「議論」という単語は 「意見」に置き換える
#118 

文言の変更（「議論」-> 「意見」、〇〇議論 -> 〇〇件）

---

client/components/charts/TreemapChart.tsx

- 階層図にホバー時に表示される Tooltip にクラスタの概要（takeaway）を表示するようにしました
- issue 上では元々表示していた件数や割合は削除した方が見やすいという意見があったので、その方向で実装しました
> ツールチップには件数/割合があるとごちゃごちゃしている印象を抱いたので、個人的に件数/割合は省いた方が見やすいと感じました
> ref: https://github.com/digitaldemocracy2030/kouchou-ai/issues/14#issuecomment-2745205016
- fix: https://github.com/digitaldemocracy2030/kouchou-ai/issues/14

階層図ホバー時にクラスタの概要説明を表示

---

Makefile

- Makaefile中の不要なターゲットが残っていたので削除しました
> Makefileのazure-acr-loginターゲットってACR名を置き換えてないから一般的には動かないし、どこからも呼ばれてないように思いますが盲腸ですかね？
https://w1740803485-clv347541.slack.com/archives/C08F7JZPD63/p1743423114579229

不要なターゲット(azure-acr-login)を削除

---

server/broadlistening/pipeline/services/llm.py

Azureのchat extractionの中でenvが不完全であるときに、チェックしてAssertionErrorを投げていたが、上流でcatchしてAPI呼び出しのエラーとして扱っていた
そもそも環境変数の正しさを毎回のAPI呼び出し時にチェックする必要はない、もっと早い段階でチェックすべき
何が間違っているのかも分かりやすくなった
```
kouchou-ai-dev-api-1           |     assert os.getenv("AZURE_EMBEDDING_API_KEY")
kouchou-ai-dev-api-1           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

fix assertion position

---

client/components/report/ClusterOverview.tsx

-  レポートの詳細ページのクラスターの見出しにリンクをつけました
https://github.com/user-attachments/assets/a885796d-6fd5-44f5-b70e-49efdce7ff99
- リンクの href, id 属性は、URL から意味が把握しやすいと思ったので見出しの日本語の文字列を設定しています
- レポートの個別ページに同じ見出しのクラスターは出てこないことを前提にしているので、認識違いがあればコメントいただけると :pray:
- クリックできるとわかりやすいように hover 時にアイコンを表示しました
- fix: #112

クラスタ見出しをanchorにする

---

client-admin/app/create/page.tsx

- タイトルの通り
- 並列実行数についても見た目を揃えるために同様に修正
現状では大きく値を変更しようとするとボタンをたくさん押す必要があってユーザーに負担がかかるため
#222 

意見グループ（クラスタ）数の値の変更を直接入力でも可能にする

---

client/components/report/Analysis.tsx

Analysis上で、「意見が含まれるコメント数」 -> 「コメント数」に文言を修正
* 実装の実態として、「意見が含まれるコメント数」ではなく元データ内の単純な「コメント数」を計算しており、文言と実態が合っていない
* また、件数を表示するうえでも、入力データ全体の件数が表示されている方が自然
* 「コメント数」と「抽出された意見数」の間に「意見が含まれるコメント数」を入れる
Close https://github.com/digitaldemocracy2030/kouchou-ai/issues/238

「意見が含まれるコメント数」 -> 「コメント数」に文言を修正

---

docs/azure-blob-storage-guide.md
scripts/README.md
scripts/assign_storage_role.sh
scripts/upload_reports_to_azure.py

- Azure Blob Storageにローカルのレポートをuploadするscriptを追加した
- 実環境で動作確認済み
- Azure Blob Storage導入後に生成されたレポートは永続化されるが、それ以前のものは別途Azure Blob Storageに入れる必要があるため
- https://github.com/digitaldemocracy2030/kouchou-ai/issues/260

Azure Blob Storageにローカルのレポートをuploadするscript

---

.gitignore
CONTRIBUTING.md
client-admin/app/create/page.tsx
client-admin/app/layout.tsx
client/app/layout.tsx
client/app/page.tsx
client/components/charts/ScatterChart.tsx
client/type.d.ts
lefthook-local.sample.yml
lefthook.yml
package-lock.json
package.json

- [Lefthook](https://github.com/evilmartians/lefthook) を使って、Git Hooks の pre-push で Biome の Lint を実行できるようにしました
- CONTRIBUTING.md に client, client-admin のコードチェックに関する記載を追加しました
- 動作確認をしている際にフォーマット漏れのコードがあったので、Biome のフォーマットを適用しました
-  Lefthook はデフォルトでは off にしていて、設定ファイルを作成することで on になる設計にしています
- 理由: 現状の Lefthook の設定は frontend のコードのみで、server 側の開発をする人にも有効にした場合に弊害が出る可能性を避けたかった
- 最初は安全側に倒して、導入してみて良さそうであればデフォルトで on に変えても良いかもしれません
- pre-commit で毎回チェックすると少し煩雑かなと思ったので、pre-push でチェックするようにしました
- fix: #84 

frontend のコードを push する際に Biome の Lint を実行できるようにする

---

client/components/charts/ScatterChart.tsx
client/components/charts/TreemapChart.tsx
client/components/report/Chart.tsx

全画面表示の「全画面終了」ボタンの後ろに要素の要約文が一部隠れてしまい、読めないことがある。
https://github.com/digitaldemocracy2030/kouchou-ai/issues/278
- `client/components/charts/ScatterChart.tsx` と`client/components/charts/TreemapChart.tsx` の props に `onHover` 用のfunctionを追加。 `onHover` が有効であることは以下で確認： https://github.com/plotly/react-plotly.js/blob/master/src/factory.js
- `client/components/report/Chart.tsx` に `onHover` 用のfunctionを実装。内容は「全画面終了ボタンと要約文の吹き出しが重なる場合に重ならなくなる位置まで吹き出しを下方向にずらす」。
○
- 全画面表示でない場合は挙動が変わらない
- 要約文がボタンに隠れない場合は挙動が変わらない
- 要約文がボタンに隠れる場合は、一番右上の要素でなくとも被らなくなるまで要約文が下方向にずれる
- 下方向にずれた場合、要約文の背景が吹き出し型であれば吹き出しの先端だけ元の位置に紐づく
△
- `ScatterChart` の場合、マウス移動のたびに `onHover` と `onUnhover` が交互に発火されるのだが、 `onHover` のたびに要約文が再描画され、本修正の位置ずらしがリセットされてしまう。そのため、 `ScatterChart` ではsetTimeoutで位置ずらしを実行するタイミングを遅らせている。これにより概ね意図通り動作するようになったが、マウスの動かし具合に …

fix issue #278 : 要約文が「全画面終了」ボタンの後ろに隠れないようにする

---

client/components/charts/SelectChartButton.tsx
client/components/report/ClientContainer.tsx
client/components/ui/radio-card.tsx

https://w1740803485-clv347541.slack.com/archives/C08F7JZPD63/p1743685246693499
>少ないデータに「濃い意見グループ」分析をかけた時に何が起こるか
>- getDenseClusters関数が末端グループを対象に濃度でのフィルタリングをする。この時「最小クラスタサイズ」の制約があるのでみんな小さすぎる時はフィルター結果が空になる。このフィルターは末端グループだけフィルターし、親グループはそのまま残す仕組みになっている。
>- フィルターされた結果を受け取ったChartコンポーネントは、チャートの種類選択が「濃い意見グループ」の時、データから一番深いグループを計算してそのレベルのグループを表示する。このとき「本来の末端グループがすべてフィルターされてる」ことで、上位のグループが表示されてしまう
>- 修正案: getDenseClustersが「フィルター結果がemptyか」のbooleanをセットで返すようにし、emptyな時には「濃い意見グループ」のボタンをdisabledにする
- #96

濃いクラスタ抽出で対象となるクラスタがない時にはボタンをdisabledにする

---

client-admin/app/page.tsx

- レポート一覧画面で各カードにマウスオーバーするとカードがグレーになり、中央に「レポートを表示」というボックスが表示される
- カード全体(既存のボタンを除く)をクリックするとレポートが開く
- 既存のレポートページへ飛ぶアイコンは削除
- 初見のユーザーがどこをクリックしていいか分からない問題があった
- マウスオーバー効果でクリッカブルであることが分からない層にも伝わるように「レポートを表示」を出すようにした
- 既存のレポート表示ボタンは重複するので削除した
#207 

レポート一覧のクリック可能範囲を広げる(#207)

---

client-admin/app/page.tsx
client/package-lock.json

- CSVダウンロードボタンを押してCSVをダウンロードするのを、Popoverを表示して通常CSVとUTF-8 BOM (Byte Order Mark) 付きのCSVを選んでダウンロードできるようにした
- 通常のCSVは「CSV」で、BOM付きは「CSV for Excel (Windows)」とした
- UTF-8 BoM付きCSVは `original-name_excel.csv` のような形式でダウンロードする
- WindowsユーザーがExcelを開くとBOM付きでないCSVは文字化けする問題がある
- 「UTF-8 BOM」という表記は非技術者に伝わりづらいため、CSV for Excel (Windows)と表現した。
#297

CSVダウンロードにBOM付きオプションを追加する

---

server/src/services/report_sync.py
server/tests/services/test_report_sync.py

* CSVダウンロード機能に用いるcsv( `final_result_with_comments.csv` )を、Azure Blob Storage連携時の削除対象から除外
* 従来は誤って削除対象になっていた
* アプリ起動時の同期対象に同ファイルを含めるよう修正
ストレージ連携をしている場合は、ストレージに出力ファイル等をアップロードをした後に容量節約のために不要なファイルを削除しているが、その際に当該のCSVファイルも削除されてしまっているためDLできなくなっていた。
当該ファイルはAzure Blob Storage上には保存されているが、アプリ起動時の同期対象からも外れておりアプリ上には存在しないため、アプリの再起動やコンテナの更新を行った場合もDLできなくなっていた。
ストレージにはcsvは保管されているので、今回の修正を反映した上でアプリ（コンテナ）を再起動すれば、以降はCSVをDLできるようになる。
Close https://github.com/digitaldemocracy2030/kouchou-ai/issues/325

CSVダウンロード機能に用いるcsvを、Azure Blob Storage連携時の削除対象から除外

---

Makefile

- make azure-cleanup 時に確認メッセージを出すようにします
- make azure-cleaup は、作成した Azure 環境をすべて削除するコマンドのため、誤って実行したときのために確認メッセージを出したほうがよいのではないか？と思いました
- 別件の作業時に make azure-cleanup を実行する機会があり、その際に気が付きました

make azure-cleanup 時に確認メッセージを出す

---

client-admin/app/create/api/report.ts
client-admin/app/create/api/spreadsheet.ts
client-admin/app/create/components/AISettingsSection.tsx
client-admin/app/create/components/BasicInfoSection.tsx
client-admin/app/create/components/ClusterSettingsSection.tsx
client-admin/app/create/components/CommentColumnSelector.tsx
client-admin/app/create/components/CsvFileTab.tsx
client-admin/app/create/components/SpreadsheetTab.tsx
client-admin/app/create/components/WarningSection.tsx
client-admin/app/create/hooks/useAISettings.ts
client-admin/app/create/hooks/useBasicInfo.ts
client-admin/app/create/hooks/useClusterSettings.ts
client-admin/app/create/hooks/useInputData.ts
client-admin/app/create/hooks/usePromptSettings.ts
client-admin/app/create/page.tsx
client-admin/app/create/types/index.ts
client-admin/app/create/utils/error-handler.ts
client-admin/app/create/utils/validation.ts

このPRでは、レポート生成ページ（client-admin/app/create/page.tsx）のリファクタリングを行いました。今後の機能追加や保守性を考慮し、コードの可読性と保守性を向上させることを目的としています。
関連する状態を各カスタムフックにまとめました
- useBasicInfo: 基本情報（タイトル、調査概要、ID）
- useInputData: 入力データ（CSVファイル、スプレッドシート）
- useAISettings: AIモデル設定（モデル、並列実行数、出力モード）
- useClusterSettings: クラスタ設定
- usePromptSettings: プロンプト設定
UIを独立したコンポーネントに分割しました
- BasicInfoSection: 基本情報入力セクション
- AISettingsSection: AI詳細設定セクション
- WarningSection: 警告メッセージセクション
- ClusterSettingsSection: クラスタ設定セクション
- CommentColumnSelector: コメントカラム選択コンポーネント
- CsvFileTab: CSVファイル入力タブ
- SpreadsheetTab: スプレッドシート入力タブ
ビジネスロジックをUIから分離しました
- api/report.ts: レポート作成API
- api/spreadsheet.ts: スプレッドシートAPI
- utils/validation.ts: バリデーション関数
- utils/error-handler.ts: エラーハンドリング関数
型定義を types/index.ts にまとめました
- …

client-admin/app/create/page.tsx のリファクタリング

---

client-admin/app/create/components/ClusterSettingsSection.tsx
client-admin/app/create/hooks/useClusterSettings.ts

- 第1階層の意見グループ数の上限を 20 -> 40に増やした
- レコメンドされる最大クラスタ数を10に変更
- こちらの議論を踏まえて修正: https://github.com/digitaldemocracy2030/kouchou-ai/pull/335#issuecomment-2816448667
- （元々のissueとは関係ない変更ですが、最大クラスタ数にかかわる変更なのでついでに修正しています）
* 現在、全体図などの散布図において意見グループの個数上限は20となっており、実際のユースケースでは20だと足りない場合があるので上限を上げたい
* ラベルが重なってしまう問題があったため上限を20にしていたが、この問題は回避策のPR（ https://github.com/digitaldemocracy2030/kouchou-ai/pull/329 ）が出されている
close https://github.com/digitaldemocracy2030/kouchou-ai/issues/330

第1階層の意見グループ数の上限を 20 -> 40に増加

---

client-admin/app/create/components/ClusterSettingsSection.tsx
client-admin/app/create/hooks/useClusterSettings.ts

- クラスター第2階層の最小値を2から4に変更した
- 第1階層の最低値が2であり、第2階層は第1階層の2倍以上となるように動的に補正がかけられている
- 理論上は4が最低値となるが、4以下に数値を設定できるため、そのたびに補正表示が出ていて少し気になる
#356 こちらのレビュー段階で見つけた
レビュー中に軽微な修正をされていたのでそのような変更ができるのかなと思ったのですが、コードに変更が入るとapproveし直しになるのかな、と思い別PRにしました。

Cluster lv2のmin valueを2から4に変更

---

client-admin/app/page.tsx

- styleを直接記述している箇所をChakra UIのStyle propsに変更
- 不要なクリック防止イベントの廃棄( #336 で触った範囲 )
- 「レポートを編集する」Dialogに関して必要な箇所をクリック防止イベントを残した
- 「レポートを編集する」Dialog外をクリックした際は、Dialogを閉じるように変更した(下記に詳細)
- レポートのクリック範囲拡大用の記述をChakra UIの LinkBox に変更 ( #316)
「レポートを編集する」に関して、Dialog表示中にDialog内とDialog外両方(=全画面)をクリックするとレポートに遷移してしまうのを防ぐためにクリック防止を導入していた。
`<Dialog.Content>` に `onClick={e => e.stopPropagation()}` を記述するとDialog内の’クリックは防止されるがDialog外をクリックすると依然として遷移する問題が残った。
`<Dialog.Root>` に `closeOnInteractOutside` を true に設定し、そもそもDialog外のクリックでDialogを閉じるようにしたところ、遷移しなくなった。挙動としては自然なので一旦この方法にした。(詳しい人いたら修正してほしい。)
- #336 のフロントのコードレビューの追加PR
#316 クリック可能範囲を広げるPR
#336 フロントのコードレビュー
内容をお読みいただき、下記のチェックボックスにチェックをつける（"- …

client-admin/app/page.tsxのリファクタリング (関連: #336)

---

client-admin/app/create/api/report.ts
client-admin/app/create/api/spreadsheet.ts
client-admin/app/create/components/AISettingsSection.tsx
client-admin/app/create/components/BasicInfoSection.tsx
client-admin/app/create/components/ClusterSettingsSection.tsx
client-admin/app/create/components/CommentColumnSelector.tsx
client-admin/app/create/components/CsvFileTab.tsx
client-admin/app/create/components/SpreadsheetTab.tsx
client-admin/app/create/components/WarningSection.tsx
client-admin/app/create/hooks/useAISettings.ts
client-admin/app/create/hooks/useBasicInfo.ts
client-admin/app/create/hooks/useClusterSettings.ts
client-admin/app/create/hooks/useInputData.ts
client-admin/app/create/hooks/usePromptSettings.ts
client-admin/app/create/page.tsx
client-admin/app/create/types/index.ts
client-admin/app/create/utils/error-handler.ts
client-admin/app/create/utils/validation.ts

- AISettingsSection.tsx を変更し、内部で usePromptSettings を使わず、親から props として promptSettings を受け取るようにしました
- page.tsx を変更し、既存の promptSettings を AISettingsSection コンポーネントに渡すようにしました
- revertされていたリファクタリングを再適用
クラスタ数やLLMモデルの変更は確認した。
Roo Code(Claude 3.7)による各コンポーネントで同様の問題が起きていないかの調査
- BasicInfoSection - 問題なし。すべての状態とハンドラーを props として受け取っています。
- CsvFileTab - useClusterSettings をインポートしていますが、実際には使用していません(型情報を使用)。props として clusterSettings を受け取っているので問題ありません。
- ClusterSettingsSection - 問題なし。すべての状態とハンドラーを props として受け取っています。
SpreadsheetTab - useClusterSettings をインポートしていますが、実際には使用していません(型情報を使用)。props として clusterSettings を受け取っているので問題ありません。
- WarningSection - 静的コンポーネントで、内部で状態を持っていません。
CommentColumnSelector - 問題なし。すべての状態とハンドラーを props として受け取っています
各段階で更新文字列を確認した
各段階でモデルが変更されていることを確認
- …

プロンプトの編集バグを修正しclient-adminのリファクタリングを再適用する

---

.github/requirements.txt
.github/scripts/review_issue.py
.github/workflows/issue-review.yml

- Issue起票時にGithub Actionsで内容をチェックし、以下の観点で相応しいラベルを付与します
- ~公序良俗に反するかどうか~
- ~既存のIssueと重複するかどうか~
- タイトルの先頭の[text]や絵文字
- タイトルと本文の内容
- 1つのIssueが複数の属性を持ちうるため、タイトルの先頭の[text]や絵文字ではなく、複数指定もフィルタもしやすいラベルを活用したい。
- しかし、ラベルを付与できるのはWrite権限以上を持つユーザーに限られる。
- そのため、ラベルの管理コストがメンテナに集中してしまう。
#409

Solve #409 automate Issues labeling with Github Actions and LLM

---

.env.example
client-admin/app/environment/page.tsx
client-admin/app/page.tsx
server/src/routers/admin_report.py

- 管理画面の追加
- とりあえずOpenAIのAPIを一発叩いてみて、動作確認
- エラーが出たら、エラーを分かりやすく表示
- envでAPIKeyが正しく設定されているか分からない
- APIのデポジットに正しくチャージされているか分からない

Client-AdminにChatGPTのAPIKeyの確認画面の追加

---

Makefile

- client-build-static実行時にルートに.nojekyllファイルを追加する
- Github Pagesにデプロイする際にjeykllで処理されてしまうのを防ぐために.nojekyllが必要
- .nojekyll ファイルをユーザーに手動で追加させるよりもビルド時に作成したほうが罠を踏むのを減らせる
- .nojekyll ファイルがあることで他のホスティングへのデプロイに特に影響はない(はず)
- #235 の着手に先立って.nojekyllをルートに追加する
#235 

client-build-static実行時にルートに.nojekyllファイルを追加する
