digitaldemocracy2030/kouchou-ai

client-admin/app/create/page.tsx
- 不要なセミコロンを削除します
- #74 の対応時に不要なセミコロンが入ったコードをコミットしてしまっていたのに #73 で気がつきました
- 本リポジトリへのコントリビュートには、[コントリビューターライセンス契約（CLA）](https://github.com/takahiroanno2024/kouchou-ai/blob/main/CLA.md)に同意することが必須です。
=> 不要なセミコロン(;) を削除

client/components/Footer.tsx, utils/dummy-server/public/meta/metadata.json
- metadata リンク先の修正
- プロジェクト紹介ページを用意したのでリンク先を修正した
- なし
=> プロジェクト概要URLの修正

.env.example, server/broadlistening/pipeline/services/llm.py, server/broadlistening/pipeline/steps/embedding.py
- Azure OpenAI ServiceのChatCompletionとEmbeddingのモデルを使ってレポートの作成が可能になった
- see 関連Issue
https://github.com/digitaldemocracy2030/kouchou-ai/issues/89
Issue #58 も半分解決されています
=> Azure OpenAIでレポートの作成を可能にする

.github/ISSUE_TEMPLATE/doc.md
=> Issue Templateにdocを追加

CONTRIBUTING.md
* コードオーナーに西尾さんを追加する文言をドキュメントに追記
* より迅速にレビューを回すため
=> コードオーナーに西尾さんを追加

client-admin/app/create/page.tsx, client-admin/components/ui/file-upload.tsx
FileUploadList 関連のコンポーネントに onRemove プロパティを追加
別件の修正をしようとしている際にエラーが出ていることに気がつきました
#142 
=> fix: Unknown event handler property `onFileRemove`. It will be ignored.

client/components/report/Analysis.tsx
- ここに変更の概要を記載してください
- ここに変更が必要となった背景を記載してください
関連するIssueのリンクをこちらに記載してください
=> /を分数に見えなくするために→に変えた

client-admin/app/create/page.tsx, server/src/routers/spreadsheet.py, server/src/services/spreadsheet_service.py, server/src/utils/validation.py
- 「データをクリアして再入力」を押した時に、既に保存したデータがあれば削除するようにしました
- 現状では[不要なデータが残ってしまうことがある](https://github.com/digitaldemocracy2030/kouchou-ai/pull/182#discussion_r2013473586)
#184 
=> 「データをクリアして再入力」を押した時に、既に保存したデータがあれば削除

client-admin/app/create/page.tsx
- csv/スプレッドシートのアップロード/取得時にカラム名の一覧を取得してドロップダウンを作成
- commentという名前を探し、ある場合はデフォルトでそれを選択（なければ「選択してください」が表示）
- /admin/reportsエンドポイントに渡すコメントデータはそこで指定されたカラムのデータが使われる
- すでにあるデータを分析する際、カラム名を手動でcommentに変更する手間を省ける
- Close #116 
=> add column selection

client/app/page.tsx
* clientの一覧画面でISRを有効化
* 5分毎に更新を実施
* これにより、作成した新規のレポートが一覧画面に表示されるようになった
* clientの一覧画面においては、ISRが設定されておらず、新規のレポートを作成してもbuildを再実行しないかぎり一覧画面に反映されなかった
Close https://github.com/digitaldemocracy2030/kouchou-ai/issues/212
=> clientの一覧画面でISRを有効化

client/app/utils/__tests__/api.test.ts, client/app/utils/__tests__/cluster-num.test.ts, client/jest.config.js, client/jest.setup.js, client/package-lock.json
- `npm i` 実行後に client の package-lock.json で差分が出ないようにしました
- 新たに client に追加されたコードに Biome のフォーマットを適用しました
- https://github.com/digitaldemocracy2030/kouchou-ai/pull/247/commits/3a7ad517ed90b3a121dd835fbb93d6d1c00277f5 の commit で ESLint を削除する修正がデグレしていたのでもとに戻しました
- Biome のコードフォーマットをチェックする CI があっても良さそうなので、この後 issue だけ作ろうと思います 📝 
関連するIssueのリンクをこちらに記載してください
=> client の package-lock.json に差分が出る課題の修正

Makefile
- #258 の変更により、想定外の環境でデグレが発生しているため一旦もとに戻す
- コメントはこちら: https://github.com/digitaldemocracy2030/kouchou-ai/pull/258#issuecomment-2792560274
=> revert #258

client-admin/app/page.tsx, server/src/routers/admin_report.py
close #277 
- server/serc/routers/admin_report.py
- ステータスの追加・修正
-  client-admin/app/page.tsx
- useReportProgressPollの修正
- ReportCardの修正
- リロードなしで画面更新するようにしました
エラーが発生した場合
処理が成功した場合
> 正常に動作するとstep1(抽出)からstep8(可視化)まで自動更新され、その後レポートのURLが表示されるが、
> エラーで落ちると進捗が更新されず、ページを再読込して初めてエラーになったことが可視化される。
#277 
=> エラーで落ちても進捗状況を自動更新する

README.md
- ここに変更の概要を記載してください
- ここに変更が必要となった背景を記載してください
https://github.com/digitaldemocracy2030/kouchou-ai/issues/298
=> docker-compose → docker compose

docs/windows-setup.md, setup_win.bat
このPRはIssue #300に対応し、Windows環境でのkouchou-aiのセットアップを簡素化するための実装を提供します。
1. `setup_win.bat` - Windowsユーザー向けセットアップスクリプト
- Docker Desktopの起動確認
- OpenAI APIキーの入力プロンプト
- 環境変数の自動設定
- docker composeによるサービス起動
2. `docs/windows-setup.md` - Windows環境でのセットアップ手順ドキュメント
- 前提条件の説明
- Docker Desktopのインストール手順
- リポジトリのダウンロード方法
- OpenAI APIキーの取得方法
- セットアップの実行手順
- トラブルシューティング
このPRにより、以下のユーザーストーリーが実現されます：
- Docker Desktopをインストール
- zipでrepoをダウンロード
- OpenAI APIキーを取得してくらいチャージする
- setup_win.batを実行
- ブラウザでアクセス可能になる
これをマージした後で、Windowsユーザに`docs/windows-setup.md`の手順でセットアップができるか試してもらう
=> Windows環境でのセットアップ簡素化 (Issue #300)

client-admin/app/create/page.tsx, client/package-lock.json
以下の注意書きをAlertコンポーネントでレポート作成ボタンの上に追加 ([@nasuka案](https://github.com/digitaldemocracy2030/kouchou-ai/issues/61#issuecomment-2795883061)) 
- レポートの作成には数分から数十分程度の時間がかかります
- 作成が完了したレポートが一覧画面に反映されるまで5分程度かかります
> 新しいレポートが生成されてから、閲覧可能になるまでの間には約５分のラグがある
> これは client で ISR を行っており、この頻度を 300sec にしているのが原因（この仕組み自体は問題ない認識）
> この仕組みを知らないとレポート作成者が迷ってしまうので、５分遅れる旨を client-admin に書くとよさそう
#61 
=> レポート作成時にISR関連の注意書きを追加する

Makefile
https://github.com/digitaldemocracy2030/kouchou-ai/issues/214
- Azureの更新のためのターゲットを追加
https://github.com/digitaldemocracy2030/kouchou-ai/issues/214
=> Azureの更新のためのターゲットを追加

client/app/[slug]/_op-image.tsx
静的サイト出力時のOGP画像生成の安定化。`OpImage` 関数内のAPIデータ取得処理にリトライ機構を追加します。
現在の静的サイト出力（`make client-build-static`）において、特にレポート数が多い場合に、OGP画像生成プロセス（`client/app/[slug]/opengraph-image.png/route.ts` から呼ばれる `OpImage` 関数）がAPIからのデータ取得に失敗し（`Workspace failed`）、ビルドが中断される問題が確認されています。
この問題は、Next.jsの静的エクスポートが複数のOGP画像を並列で生成する際に、起動したばかりのAPIサービスへの同時多数アクセスが集中し、APIがリクエストを処理しきれない、あるいは一時的な通信エラーが発生することが原因と推測されます。エラーは非決定的（ランダム）に発生し、処理対象のレポート数が多いほど顕著になります。
この変更は、APIの準備が整う前のアクセスや、瞬間的な高負荷による一時的な通信失敗を吸収するため、`client/app/[slug]/_op-image.tsx` 内のAPI fetchにリトライ処理を導入することで、静的サイト出力の安定性を向上させることを目的としています。
#343 
=> Bug修正: static build時のOGP画像のリトライ処理を実装

.github/ISSUE_TEMPLATE/algorithm.md
* アルゴリズムの実験結果をまとめる場所をテンプレートに追記
* アルゴリズムの実験結果をまとめる場所について、assignee がどこにまとめるべきか戸惑ってしまう課題があったのでテンプレートに追記
=> アルゴリズムのイシューテンプレートをアップデート

CONTRIBUTING.md
=> add mtane0412 to maintainer

client/app/[slug]/_op-image.tsx
- report数分だけfetchFontでGoogle Fontsをダウンロードしていたのをフォントキャッシュオブジェクトに保存して再利用するようにした
- 静的ページを25出力しているが、引き続きmake client-build-staticが安定しない ( #343 と同様のエラー)
- #344 の修正を行ったが、HTTPエラーは出ておらず、別の要因でビルドがクラッシュしている可能性
- fetchFontがページ数分callされているので25 pages * 2 font weight = 50 font filesのダウンロードになってクラッシュしてるという推測でフォントキャッシュを作成した。一旦エラーが落ち着いたのでプルリクにしておく
#343 
#344 
=> static build時のフォントキャッシュを追加

.env.example, compose.yaml, server/Dockerfile, server/requirements-torch.txt
- api コンテナの build 時間を短縮するため、GPU を使わない場合にはより適切なパッケージ(torch の GPUサポートなし）のインストールを行うようにしました
- これにより、GPU を使わない場合は api の build 時間が従来の半分以下程度（マシンスペックやネットワーク環境次第ですが、手元の環境では 17 -> 7分）になります
- セットアップを試した方からセットアップ時間についてフィードバックがあった
- ここ最近、作業時に build 時間が伸びた気がしていた
- 他にも build 時間が長くなったと感じている人がいた
- [調査](https://github.com/digitaldemocracy2030/kouchou-ai/issues/432#issuecomment-2850411787)の結果、セットアップ時間の大半は api の build （特に nvidia-* 系のパッケージのインストール）処理だった
- これらのパッケージ（のGPUサポート）は、GPUによる処理を行わない場合には不要と思われる
- （おそらく）GPUによる処理を行うユーザーは一部
https://github.com/digitaldemocracy2030/kouchou-ai/issues/432
=> api コンテナの build 時間を短縮する 

.github/scripts/review_issue.py
ラベルの自動付与処理のうち、LLMに判定させる箇所の精度が低い。
Promptを改善した。
https://docs.google.com/spreadsheets/d/1XqtM7-eEbcjku2OWjHeD9js-1nHtlNXQY2UMM83ziJo
修正前のpromptと加えて改善傾向にある。
#444
=> Labeling prompt improvement

CONTRIBUTING.md
=> ところてんさんをメンテナーに追加

server/pyproject.toml, server/requirements-dev.lock, server/requirements.lock
* APIビルド時に依存関係でエラーが起きていたので解決
* tenacityがなぜか消えていたので追加
close https://github.com/digitaldemocracy2030/kouchou-ai/issues/462
=> APIの依存関係エラーを解決

client-admin/app/create/page.tsx
- レポート作成画面の AI 関連の設定を表示するボタンのテキストを Figma に合わせて変更しました
- ref: https://www.figma.com/design/ZImSumdtUme9loVY5CejWX/%E5%BA%83%E8%81%B4AI%EF%BC%88dd2030%EF%BC%89?node-id=1223-5511&t=bHu1PLLPzNUIC108-4
- 管理画面のレポート一覧とレポート生成画面で、AI のオプションを設定する UI の文言を統一したい
- https://github.com/digitaldemocracy2030/kouchou-ai/issues/460 の残タスク
- レポート作成画面でボタンのテキストが変わっていること
動作確認の項目については、実装者による動作確認のケースが適切かを確認してください。
必要に応じてレビュアー自身による動作確認も歓迎します（必須ではありません）。
=> [client-admin] レポート作成画面のボタンの文言変更
